name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install ruby-build in the Home Directory
      - name: Install ruby-build in Home Directory
        run: |
          git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
          export PATH="$HOME/.ruby-build/bin:$PATH"

      # Install Ruby manually in a writable directory
      - name: Install Ruby manually
        run: |
          mkdir -p $HOME/.ruby
          ~/.ruby-build/bin/ruby-build 3.1.4 $HOME/.ruby/3.1.4
          export PATH="$HOME/.ruby/3.1.4/bin:$PATH"
          touch $HOME/.ruby/3.1.4.complete

      # Verify Ruby Installation
      - name: Verify Ruby Installation
        run: |
          export PATH="$HOME/.ruby/3.1.4/bin:$PATH"
          ruby --version
          gem --version

      # Install Bundler and dependencies
      - name: Install Bundler
        run: |
          export PATH="$HOME/.ruby/3.1.4/bin:$PATH"
          gem install bundler

      - name: Install Gems
        run: |
          export PATH="$HOME/.ruby/3.1.4/bin:$PATH"
          bundle install

      # Build the Jekyll site
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: |
          export PATH="$HOME/.ruby/3.1.4/bin:$PATH"
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
