name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install ruby-build and manually install Ruby
      - name: Install ruby-build
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libssl-dev zlib1g-dev
          git clone https://github.com/rbenv/ruby-build.git
          PREFIX=/usr/local ./ruby-build/install.sh

      - name: Install Ruby manually
        run: |
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64/bin
          ln -s /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/ruby /usr/local/bin/ruby
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Verify Ruby Installation
        run: |
          ruby --version
          gem --version

      # Install Bundler and dependencies
      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
